version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:11
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres

  app:
    container_name: finance-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    networks:
      - postgres
    env_file:
      - .env
    restart: on-failure
    links: 
      - postgres
    command: "npm run start:dist"
    volumes:
      - /data/app:/data/app

networks:
  postgres:
    driver: bridge
